version: "3.2"

services:
  web:
    build: .
    container_name: mohorii-web
    ports:
      - 8000:80

  db:
    image: mariadb:10.9.3
    container_name: mohorii-db
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_PASSWORD=123456789
      - MYSQL_DATABASE=mohorii_db
      - MYSQL_USER=mohoorii