version: "3.2"

services:
  web:
    image: php:8.1-apache
    volumes:
      - ./build:/var/www/html/
    ports:
      - 8000:80

#  db:
#    image: mariadb:10.5.8
#    container_name: mohorii-db
#    environment:
#      - MYSQL_ROOT_PASSWORD=123456789
#      - MYSQL_PASSWORD=123456789
#      - MYSQL_DATABASE=mohorii_db
#      - MYSQL_USER=mohoorii
